---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgA8OI+7VA8YfkJM1TUnkRHYbdwt6Z06JwePmllBgVDERffSgPf5Egafppb1hkjG1Z50rMTp0jav3pEVTtBz6ltlCgQS2Oc2DTk9GHsz+u4C3/9CFaNArdZYw6TmK/vSb72g3wrOoCl253v4haqvi53ktmg9mnh9Iv2J0C6pTPII3mqOjeX3JgD2CFIm75ihqfjHybxhw82/JJuybMWOmG1grOTpqK10AZcUw/Cj9xp3E2y8jKqQBXIsynvmgfrJpLB9ixuvyPI08XDGgX1+WSAY4f9AfkkIK10QoBpmRWN6S+1QqlmLJ6N5FRaZuzgW4z+KrDPx79g8IGOaN1JH8CYj78ICFHfT/hrBPD9xzGs9svZK4j5PBAX8wo6BlaVc7HpXXlFFTe6HpWhY6mMXdqhlfT7ZOj1Jd/T84CG+AHyxyvfk47BBDcA6rGGCygj8jHIa0QTt6AsWS2WqsI87/AvfJG8u6ryeyJz+O4++9Xrty26LF/ma1cnzykvyf0S9Rw2v6MPW/8kqwP3YjUlb+2EXKbR32NhQqZvhfpU5snfk5Uu+fwpusm1vBaiq+6rA5DD4wROEOdaU+PbXL5m+8rCBAe4u7Jrdpm0P1p3/JJzxNFPPrseij5xMZ6jkUNkqGv0ULNVTlM+RTFw0DUAKT8krUe7FV87NWwZBuEVuCUo/XEYLfEigBwOCrj2cdokmL/LSURpVuUuCyIK3nzPu5AP9sbzoV7SKH1f0jsC4Z0uAiW/7ryAF9U+sPk+cpOGb5U8hebjsRjeI2rf5CIbg0G88weSMrk+hEV/NHQ5CoGDjLIEUmKvXbRGcfZ7sD+cQiAJ/3qfvomre4t0ez5uijcbY2CaBpah9YwWukYph0D2rQw+lIrnZJSdfHfQ2757xg5nj9b/Os80SUvPW9oG7J2WSuu2ttC+0sbdznvyrkR+H6QqJpKtsoi6Kh8t9cGMU4jPP40YvEffYIQHlA3cifA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: regcred
    type: kubernetes.io/dockerconfigjson
