---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCgp83TCh9vWZRJMOxBTpj0K9ngzPyU5iACp12gWFHGCwx/WaWhGxspEE9xdMyOKzvaYVMsukr/y86Ki9pYxbpV7HewkxY9Lvsi2aQUtPdsIqpxP3dznYAF+q/WCU/YFHih/3XNXJvqJi5HVjsVF4h/PKYY2iP7MG3sJ/ipioHxMZ1fb/nOYX1wf7CUp5faVofw0Z93D/Niqpd+RXko2/vEFG9x+8s7Awct0mgUP+K2pBv5kRrBL9gowg86NS0Wlae+AxtATXV6HHpvVSm4FEA0ecps21FmrftznLRFDZS0sTwR84dbj0sHuIksEXtGDfD2DWS6c07vrH+ByEb/kEKNhe/mgpJKiAOSbY1zj3m7110BMcHgZE1O30V6rDrUQs3egPZbIt3YfSbf72cY/Gq5Lv3DDtDm2e1RjLy7MnjOj0XTyehwYslDtQL1fRgVnDpycoOuZnrZFk3hm8GU1gziE8vRlhSyxrOUdDYZ1b5ZIklqrsNv13LFNzYJKHaIDfK5ZK1IM0jaV80w+FsD70k2F0h4EnHm7juVcb4zSEigG+qYiPSa+j8awXtOri8TtA5FwKF1b4YsZ87ztHrKB9KsGHi6w8kzy9EiHtB1NEqzwzoXLXMl72yJ2kpocdh5tzr+/kjYqq0pkUuh3mjAhz+r06pd6oMr55aWSc9U+i+cvKm084AHq8YvAVZgBq31j08tS7YLYkXG8xxMHqewcwGEChSVoaQwgBnyF8CywHkN3AqK2xfVEdO7Y8tR1USU/j80/qKGxsFDIjFINoCxgG/zd/ilmv+MOtxrNcViNlb6nVBtsOqufyyWlBcgnqosJ8E+61ov1Gdhu5+s9mBHdVdhyyu6HoLLFW8oF67yhEHsU5mLJP3LAbJ/NyCzjb1Eba8d9G1Sal3MCAVVyeojJpQq
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
