---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgALlg4IwffIQZo/46kLmftKHlJNvYnWaYr/GPURxv/c6mbIZ0KCVWDVtrRXAF/9J9c7jtaQrPqhLIKubgpPwvYdvTftP5fzBiWVGg7hqGhikAM4vHUxd/GreM5SKbNePMqRFK69lJ5ZjFcSASL29EC1q4Ao8MLGvWWz7RzVf5beu20dQMpetnjhN42qIqDtoXhJWi3+tohtAwv+0njS6g33xdJ8V3BK287wCbM4aPYi37KW7D3Ntk2n8NNhSkf54nzplq3Jkr/iH/RIy2dy4CRUZplQnoR/K176znOlZH53jomu38rQwTIekaJy0TkObOJZ7tuamLwhjNIpzOfkZJbKfj1gDncEYn6zKax8LY+fEfrCn6aIqWfWG22ebD1bvqoRy44X9uS2Z4UF9JVvy0AO6fg5z1gnHSwq4BqHstiTl9+pbL1Tc8tvFge4ZKysQZvR4ywpEAB4DkexqKJfIiXTGa43a1lDhhkEHIoLrYwDPH7NB5j+dWJCoI9P4Rj2ZM/przzzxaXMG9PebjyR6mMa+CHnzU9yunb9VvTUlQEIj1D9LxEMgn2Nyz7W4OJ56mFZfS0GUSeRRzyvEE/cvxBQgEZdEuqNhL3LuoBGC5aZv9mZhmxH7G7JqipV96jmB+nlLgySDfblezwuahoxjNe7mhoyLZIbdqXICj7DI14K44kUQp3B0Hk61MrUFyPCmPc/4S8YwgKwXgviWP5FFxycwnFcJa/DPqmOW4GJwhsM+OyQWkMPlurpdHxa5aJ1lBo5jwuz/CfCKXzT5f+R7dLQ9mIqDhNdupxk5YZJDJesQbM/HOdlVT4k3M3h77EuV+5WdZ3qPpdL6qyRwUriD3grMVwjMLIP/B+h00hfrBEVBKmcn/h1BiTk0Gh2N5dQcWn6RvPNAKJ14YCa+hRXRIIX
  template:
    metadata:
      name: regcred
    type: kubernetes.io/dockerconfigjson
