---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS51bmlwcm9qZWN0LmpwIjp7InVzZXJuYW1lIjoiYXlhbmUiLCJwYXNzd29yZCI6Ikh5cGVwSFIzQUY4ViIsImVtYWlsIjoiMDFjLmF5YW5lQHVuaXByb2plY3QuanAiLCJhdXRoIjoiWVhsaGJtVTZTSGx3WlhCSVVqTkJSamhXIn19fQ==
kind: Secret
metadata:
  creationTimestamp: "2026-01-12T15:25:48Z"
  name: regcred
  resourceVersion: "1056271"
  uid: 38f22ab7-6820-4def-bea3-8720d452c98c
type: kubernetes.io/dockerconfigjson
