---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBNMnzT4OhdP3V9fNMwyHfkcY0CPHvJi/z1NFIoviDZT8Z9e/dYSy6L5uyoO6DgTIB+W8j3Wq7vhDTT8g6xH6EKkcjzBh1wtbpelBzqLGEG96v5tU1GDdeTqV05z+sBNjrOq+CNLd4ZWJhd1cbeJjfjR5daaZaQS8drrsKb6aDXJaevWXVB7PQsbXuvGeUFif8sOKNz1herRJoQr1NZHaf8THWpnaYR/cyl5wHc4UGzBLeFyvRnwbxjwABIVVhs4LXzmnF49HqgNXdDY9oGgOLaXfNWq8uPPlr6LSd7FUf0uhg+fxJsCWIZKg3MHl1C/kmWlQ+8fBDWW4vqpMfmZYyfQXHKW14/Y3ogpOP7jSn4Ph+cPpbOZxyWnE+0GxfsI3CaqX17K0luUvz5vQ7NBAB89Y8NEY+dC5wVEFFSIWTpLRQiq6eZDCqpqscAJZBCY+xLae3HfvDcRT05QYxkDdUPc8b+OQ5DiXJyDWzBDuBEdjof5izjvuepUr1WI6I8MICtUB+OmgTQZabpw7yV/QwyGyKsp5KPoNN5AxflYWfGFxmpvd0eNkDsvPCQ8WkL9kndDRr0qOnbd4AwwRj/Z/P3D7ewrlBPDwyE+e9ohQ+PPswEUWQwiDFOLys8ZmG80Q6aV1Z+mni6vimjRFYvHfD/N3DjSGkM9UyL5VNyUkyNfnVTxgybSSWWO1SbJTuAYHU+k4HzPFG/VbFMlyswA1q9vQA+045KCkb+Id7SwprkpKSQhzXM2hH34z69i7hnBZzOQccD5dNCSnLBMwm/UI4gEdF5QpEgf7Y/uBb8VgqCGO1+iuk8v/URzDkjaI/lvQomCgy3yPHg8PirlTdO9SaX+HNIMT/qD8pXaEMk1OOmMJLE2fffA7XvSGcu066g7s+WArCrAK3b
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
