---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgBgcr/6kcPO7qvdeVMpzY/LKlSrW4J/i9zEfNLYEhdUCBKrfldDaoNzMX5Aipqg1GrKZXHu5pJvyrxp1pxzCeEIg7fmfq0FXuJ1Y6AgMKKbPwmHSI3b9AvDSX4GD8NNnYIj4hxLW3e2Me6T5lrV3Ak2CblMHiGkHxfjAYVKe/u/LUFwJDiR1ICEn2g2ca326IUYkrD/ByKVLK0C/P0blCogwtYXfYYrEhK1Gt07FmuDeEojeXl5a8cOgeDscr8FAStuA82sPkSgieRqyAwxHT/g2lJexi/KTKwL7VWinVwB3TAbZtnOZIm+ihdzu4+c9f1ZaZH78cvtTRbP51a2VuKhwkaPXre2m1j5tX0N1HagTEHknzFF4GBjvkBQZbJ6+lEnj0am4KI7M6/ZF36q3UguDx+YINPFSzltydUW+niu5w0zu98ImXJTULaRkdy3BuSpS9BncZyZJsTCeEWGtEdaBcrXHQsyKpQSyHLMBwJLbcuttXywLWWgmn+qtEp2RKIA57FJBSCY7lyxF1F8xY9sT3eDdypB7XS0BHVUUfgdY6FnS8vA15KiOXsyvFqe29z6eddV+nsbBAsdTz4Mm1GLnzEK4ISzP3wBsAx7QWwh56ULmMphwEopSYvE2bCyVGxWVgRvfhq+UvW4gkv1L6K0EgX3MCaQe5KfuhBHxwclK60RHL0dfH9w61i3BvWUXrPTe2QYn7NNkfyMw7BSBG2ygohI2wHlWoYHsBXulxKl8UiEtvEZcug+djeucAz8g6o4CncPmeFiS3S7eL+Jh2MpNgFzWj95QaaW9EutWA2uJZ5aX5mjMdy8JU1YUglOxulm1TagE3rCAuiU2DnUcB4aTbwlnU9aMe2RGP4i3jlytQSt6Q22J2/X2hAZOAnMxkFmtsS9aMWL
  template:
    metadata:
      name: regcred
      namespace: default    type: kubernetes.io/dockerconfigjson
