---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgA2rtj/nVFtbtrWl9VMqmnQnvOx711yTQ+V0L8v3wOHXvf0M8jHE6ye0U+RnAgueAElPKHU0q3TBiABlYhF4QdkEB2ufCC81CRUt9qwkTteFp7u2axbIrPDf6dj+GZwk7bbcfj1c2XFJQJl1QeH2hwe2iM1ay2nk1yVUSVYLMdPchlvCmUp0m66vobBs4nwhVtV3JnpJBOPaMfvgEgwWcXS+4rXgDegoIjgizCj8ntrTPqviHsogCkoUwlbCE8qVB1k4PhG7bhGH920AWOCitKKxQcnOyuVKEbP9Xo2pw/hQTAA44kfR0IEa4FfJkJf5+MR+dQHlHHTlNRyPedgRsYU5XWUeeH5hMJ0FQUIu1uWrh7zbcUCFnjFulpqWZjG0sbQdeeH2uLBZk+V/M9mcnUGl9zzQIUqiV31KMdetX/CkTlKPglFH0Q9lKOclVRYBuVPHKI1/kutfZLV+lnoUcRXCmxWsRSJIDV/xiwd9uX1G1f+MwYOihrLTQAKPiuxgQcndBc78NKosiS81v1n9Hjo9DHIDPccwPVyg/LOp5tX+6IpKQZJqVauCaI3hdu+epUGe+sP6vbg2GKkzc78je7al1EoPMXTOGtlQkgPf0QwW+gduWATfwVxwJ21i6qi7JaarGNZLaqp4LftX5y847U86YNbU5r+waSvOWCIqW8BYQjZgaNkD+kdoLS9laeL685UOVXcd75YJlwCu2qZy+AWy85J+lmvd+xVkijyfGm2MmEc13CkfNOSF27Hd5VAA0A8QAlL6szP3Qr4OTCU2MUmXuJhdvIwXo+cyS9QHAfiy47Acu3C1SgY9Q7aSJC74R8RXmEpxDbaN0reWmP6SQGw5InxnzZUtRIIpUGa20laCdTHABwDDp8+PcNE5SOANOa1lXVsgK95
  template:
    metadata:
      name: regcred
    type: kubernetes.io/dockerconfigjson
