name: Docker Build and Push
on:
  push:
    tags:
      - "v*"

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract tag name
        run: |
          tagname=${GITHUB_REF#refs/*/} && echo "TAG_NAME=${tagname#v}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: registry.uniproject.jp
          username: ayane
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.uniproject.jp/ayane/ayane-slides-site:${{ env.TAG_NAME }}
          cache-from: type=registry,ref=registry.uniproject.jp/ayane/ayane-slides-site:buildcache
          cache-to: type=registry,ref=registry.uniproject.jp/ayane/ayane-slides-site:buildcache,mode=max
